# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_full_text_searchable}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michel Jansen"]
  s.date = %q{2010-07-16}
  s.description = %q{add full text search to ActiveModel classes (ActiveRecord, Mongoid etc.)}
  s.email = %q{mail@micheljansen.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_full_text_searchable.gemspec",
     "lib/acts_as_full_text_searchable.rb",
     "lib/full_text_search.rb",
     "test/helper.rb",
     "test/test_acts_as_full_text_searchable.rb"
  ]
  s.homepage = %q{http://github.com/micheljansen/acts_as_full_text_searchable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{add full text search to ActiveModel classes}
  s.test_files = [
    "test/helper.rb",
     "test/test_acts_as_full_text_searchable.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

